drinks = [
  "Dirty Martini",
  "Gibson",
  "Gimlet",
  "Gin Fizz",
  "Gin Sour ",
  "Gin and Tonic",
  "Greyhound",
  "Lime Rickey",
  "Martini",
  "Negroni",
  "Pimm's Cup No. 1",
  "Singapore Sling",
  "Sloe Gin Fizz",
  "Tom Collins",
  "Blue Hawaii",
  "Blue Hawaii",
  "Bahama Mama",
  "Blue Hawaii",
  "Cuba Libre",
  "Dark and Stormy ",
  "Daiquiri",
  "Hot Buttered Rum",
  "Hurricane",
  "Mai Tai",
  "Mojito",
  "Piña Colada",
  "Planter's Punch",
  "Zombie",
  "Bloody Maria",
  "Juan Collins",
  "Frozen margarita",
  "Habanero margarita",
  "Tamarind and Tequila",
  "Tequila Sunrise",
  "Tequila Sunset",
  "Cosmopolit an",
  "Appletini",
  "Bloody Mary",
  "Cape Cod",
  "Cosmopolitan",
  "Greyhound",
  "Kamikaze",
  "Lemon Drop Martini",
  "Mudslide",
  "Screwdriver",
  "Sea Breeze",
  "Sex on the Beach",
  "Smith and Wesson",
  "Vodka and Tonic",
  "Vodka Collins",
  "Vodka Gimlet",
  "Vodka Martini",
  "Vodka Red Bull",
  "White Russian",
  "Highball",
  "Hot Toddy",
  "Irish Coffee",
  "Jack and Coke",
  "Lynchburg Lemonade",
  "Manhattan",
  "Mint Julep",
  "Old Fashioned",
  "Seven and Seven",
  "Sneaky Pete",
  "Whiskey Sour",
  "Long Island Iced Tea",
  "Long Island Iced Tea",
  "Amaretto Sour",
  "Boston Sidecar",
  "Brandy Alexander",
  "Electric Lemonade  ",
  "Fuzzy Navel",
  "Harvey Wallbanger",
  "Long Island Iced Tea",
  "Melon Ball  ",
  "Metropolitan ",
  "Smith and Kearns"
]

drinks.each do  |drink|
  Drink.create(term:drink)
end
